style: Minor changes

diff --git a/resolve-fix b/resolve-fix
--- a/resolve-fix
+++ b/resolve-fix
@@ -1,17 +1,44 @@
 #!/bin/bash
 
-###
-# name = DaVinci Resolve Libs fix
-# version = 1.0.0
-# description = Bash Script
-# authors = @gabrielcapilla
-# license =
-# repository = https://github.com/gabrielcapilla/resolve-lib-fix
-# edition = 2024
-# idiom = english, spanish
-###
+readonly optResolveLibs="/opt/resolve/libs/"
+readonly disabledFolder="${optResolveLibs}_disabled"
 
-function getLang() {
+declare -A print=(
+  [es_makeFolder@message]="Creando carpeta _disabled en $optResolveLibs"
+  [en_makeFolder@message]="Creating _disabled folder in $disabledFolder"
+
+  [es_makeFolder@success]="Carpeta _disabled creada correctamente en $optResolveLibs"
+  [en_makeFolder@success]="_disabled folder created successfully in $optResolveLibs"
+
+  [es_moveFiles@message]="Moviendo bibliotecas a $disabledFolder"
+  [en_moveFiles@message]="Moving libraries to $disabledFolder"
+
+  [es_moveFiles@success]="Bibliotecas movidas correctamente a $disabledFolder"
+  [en_moveFiles@success]="Libraries moved successfully to $disabledFolder"
+
+  [es_makeFolder@error]="Error al crear la carpeta _disabled en $optResolveLibs"
+  [en_makeFolder@error]="Error creating _disabled folder in $disabledFolder"
+
+  [es_moveFiles@cdError]="Error al cambiar al directorio $optResolveLibs"
+  [en_moveFiles@cdError]="Error changing to directory $optResolveLibs"
+
+  [es_moveFiles@mvError]="Error al mover las bibliotecas a $disabledFolder"
+  [en_moveFiles@mvError]="Error moving libraries to $disabledFolder"
+
+  [es_main@libsError]="Error: $optResolveLibs no existe"
+  [en_main@libsError]="Error: $optResolveLibs does not exist"
+
+  [es_main@success]="Proceso completado correctamente"
+  [en_main@success]="Process completed successfully"
+
+  [es_main@mvError]="Error: Error al mover las bibliotecas a $disabledFolder"
+  [en_main@mvError]="Error: Failed to move libraries to $disabledFolder"
+
+  [es_main@error]="Error: Error al crear $disabledFolder"
+  [en_main@error]="Error: Failed to create $disabledFolder"
+)
+
+function lang() {
   local lang=${LANG:0:2}
   local available=("es" "en")
 
@@ -22,94 +49,55 @@ function getLang() {
   fi
 }
 
-function getText() {
+function print() {
   local action=$1
   local lang
-  lang=$(getLang)
+  lang=$(lang)
   local key="${lang}_${action}"
-
-  local -A print=(
-    [es_makeFolder@message]="Creando carpeta _disabled en $optResolveLibs"
-    [en_makeFolder@message]="Creating _disabled folder in $disabledFolder"
-
-    [es_makeFolder@success]="Carpeta _disabled creada correctamente en $optResolveLibs"
-    [en_makeFolder@success]="_disabled folder created successfully in $optResolveLibs"
-
-    [es_moveFiles@message]="Moviendo bibliotecas a $disabledFolder"
-    [en_moveFiles@message]="Moving libraries to $disabledFolder"
-
-    [es_moveFiles@success]="Bibliotecas movidas correctamente a $disabledFolder"
-    [en_moveFiles@success]="Libraries moved successfully to $disabledFolder"
-
-    [es_makeFolder@error]="Error al crear la carpeta _disabled en $optResolveLibs"
-    [en_makeFolder@error]="Error creating _disabled folder in $disabledFolder"
-
-    [es_moveFiles@cdError]="Error al cambiar al directorio $optResolveLibs"
-    [en_moveFiles@cdError]="Error changing to directory $optResolveLibs"
-
-    [es_moveFiles@mvError]="Error al mover las bibliotecas a $disabledFolder"
-    [en_moveFiles@mvError]="Error moving libraries to $disabledFolder"
-
-    [es_main@libsError]="Error: $optResolveLibs no existe"
-    [en_main@libsError]="Error: $optResolveLibs does not exist"
-
-    [es_main@success]="Proceso completado correctamente"
-    [en_main@success]="Process completed successfully"
-
-    [es_main@mvError]="Error: Error al mover las bibliotecas a $disabledFolder"
-    [en_main@mvError]="Error: Failed to move libraries to $disabledFolder"
-
-    [es_main@error]="Error: Error al crear $disabledFolder"
-    [en_main@error]="Error: Failed to create $disabledFolder"
-
-  )
-  printf "%s" "${print[$key]:-${print["${lang}_default"]}}"
+  printf "%s" "${print[$key]}"
 }
 
 function makeFolder() {
-  printf "%s\n" "$(getText makeFolder@message)"
+  printf "%s\n" "$(print makeFolder@message)"
 
   if sudo mkdir -p "$disabledFolder"; then
-    printf "%s\n" "$(getText makeFolder@success)"
+    printf "%s\n" "$(print makeFolder@success)"
     return 0
   else
-    printf "%s\n" "$(getText makeFolder@error)" >&2
+    printf "%s\n" "$(print makeFolder@error)" >&2
     return 1
   fi
 }
 
 function moveFiles() {
-  printf "%s\n" "$(getText moveFiles@message)"
+  printf "%s\n" "$(print moveFiles@message)"
 
   if cd "$optResolveLibs" && sudo mv libgio* libglib* libgmodule* libgobject* "$disabledFolder"; then
-    printf "%s\n" "$(getText moveFiles@success)"
+    printf "%s\n" "$(print moveFiles@success)"
     return 0
   else
-    printf "%s\n" "$(getText moveFiles@cdError)" >&2
-    printf "%s\n" "$(getText moveFiles@mvError)" >&2
+    printf "%s\n" "$(print moveFiles@cdError)" >&2
+    printf "%s\n" "$(print moveFiles@mvError)" >&2
     return 1
   fi
 }
 
 function main() {
-  readonly optResolveLibs="/opt/resolve/libs/"
-  readonly disabledFolder="${optResolveLibs}_disabled"
-
   if [ ! -d "$optResolveLibs" ]; then
-    printf "%s\n" "$(getText main@libsError)" >&2
+    printf "%s\n" "$(print main@libsError)" >&2
     exit 1
   fi
 
   if makeFolder; then
     if moveFiles; then
-      printf "%s\n" "$(getText main@success)"
+      printf "%s\n" "$(print main@success)"
       exit 0
     else
-      printf "%s\n" "$(getText main@mvError)" >&2
+      printf "%s\n" "$(print main@mvError)" >&2
       exit 1
     fi
   else
-    printf "%s\n" "$(getText main@error)" >&2
+    printf "%s\n" "$(print main@error)" >&2
     exit 1
   fi
 }
